#!/bin/bash
# Installs a git pre-commit hook that auto-regenerates dashboard JSON
# from local markdown files before every commit.
# Run once from the project root: bash scripts/install-hooks.sh

set -e

HOOK_PATH=".git/hooks/pre-commit"

cat > "$HOOK_PATH" << 'HOOK'
#!/bin/bash
# Auto-regenerated by install-hooks.sh — do not edit manually.
if [ -d "data" ]; then
  echo "[pre-commit] Regenerating dashboard data..."
  if command -v node &>/dev/null; then
    node scripts/parse-data.js
  elif docker ps --filter name=nodejs --format '{{.Names}}' | grep -q nodejs; then
    docker exec nodejs node /app/scripts/parse-data.js
  else
    echo "[pre-commit] ⚠  No Node.js found locally and 'nodejs' container not running."
    echo "             Start it with: bash /Users/daniel-mbp/Playground/Docker/NodeJs/start-nodejs-headless.sh"
    exit 1
  fi
  git add docs/data/
  echo "[pre-commit] docs/data/ updated and staged."
fi
HOOK

chmod +x "$HOOK_PATH"
echo "✓ Pre-commit hook installed at $HOOK_PATH"
